export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const CLEAR_VALUES = 'CLEAR_VALUES';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CREATE_INVOICE_BEGIN = 'CREATE_INVOICE_BEGIN';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_ERROR = 'CREATE_INVOICE_ERROR';
